# permissions for end users to edit mydeployments.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: mydeployment-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: controller-demo
    app.kubernetes.io/part-of: controller-demo
    app.kubernetes.io/managed-by: kustomize
  name: mydeployment-editor-role
rules:
- apiGroups:
  - apps.demo.cnoe.io
  resources:
  - mydeployments
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - apps.demo.cnoe.io
  resources:
  - mydeployments/status
  verbs:
  - get
